# Generated by Django 5.2.6 on 2025-09-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendToSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRMData', models.JSONField(max_length=9999)),
            ],
        ),
        migrations.DeleteModel(
            name='StringBoolPair',
        ),
    ]
