# Generated by Django 5.2.6 on 2025-09-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sendtosi_delete_stringboolpair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendtosi',
            name='CRMData',
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Account_ID',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Account_Name',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='D_tools_Budget',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='D_tools_Project_Id',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Deal_ID',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Deal_Name',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Jobsite_City',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Jobsite_Code',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Jobsite_Country',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Jobsite_State',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Jobsite_Street',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Progress',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Project_Close_Date',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Project_Start_Date',
            field=models.JSONField(default=123, max_length=999),
            preserve_default=False,
        ),
    ]
