# Generated by Django 5.2.6 on 2025-09-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sendtosi_crmdata_sendtosi_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendtosi',
            name='D_tools_Budget',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='D_tools_Project_Id',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='Jobsite_City',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='Jobsite_Code',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='Jobsite_Country',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='Jobsite_State',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='Jobsite_Street',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='Project_Close_Date',
        ),
        migrations.AlterField(
            model_name='sendtosi',
            name='Account_ID',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='sendtosi',
            name='Account_Name',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='sendtosi',
            name='Deal_ID',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='sendtosi',
            name='Deal_Name',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='sendtosi',
            name='Progress',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='sendtosi',
            name='Project_Start_Date',
            field=models.JSONField(),
        ),
    ]
