# Generated by Django 5.2.6 on 2025-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sendtosi_d_tools_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtosi',
            name='Mission_ID',
            field=models.JSONField(default=122),
            preserve_default=False,
        ),
    ]
