# Generated by Django 5.2.6 on 2025-09-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sendtosi_mission_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendtosi',
            name='Account_ID',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='Project_Start_Date',
        ),
    ]
