# Generated by Django 5.2.6 on 2025-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_sendtosi_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendToCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.JSONField()),
            ],
        ),
    ]
