# Generated by Django 5.2.6 on 2025-09-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sendtocrm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendtocrm',
            name='Data',
        ),
        migrations.AddField(
            model_name='sendtocrm',
            name='ApiKey',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtocrm',
            name='Ids',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtocrm',
            name='Module',
            field=models.CharField(default={}, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtocrm',
            name='Type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtocrm',
            name='UpdatedOn',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
