# Generated by Django 5.2.4 on 2026-01-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sendtosi_closing_date_sendtosi_engineering_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendtosi',
            name='Closing_Date',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='Engineering_Lead',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='Project_Manager',
        ),
        migrations.RemoveField(
            model_name='sendtosi',
            name='SI_Template',
        ),
    ]
