# Generated by Django 5.2.4 on 2026-01-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_sendtosi_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtosi',
            name='Closing_Date',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Engineering_Lead',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Owner',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Project_Manager',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='SI_Template',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
